include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  errors:
    only_throw_errors: ignore
    unused_shown_name: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - test/**.mocks.dart
    - lib/**/generated/**.dart
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
